name = input("What is your name? ")
age = int(input("How old are you? "))
location = input("Where do you live? ")
salary=int(input("how much do you earn? "))
department=input("which department do you work with? ")
print(f"Hello {name}, you are {age} years, coming from {location},earning {salary}, from {department}.")